version: '3.9'
services:
  main:
    container_name: main
    build:
      context: .
      target: final
    volumes:
      - sqlite:/data/sqlite
    privileged: true
    ports: 
      - 8080:8080
    restart: unless-stopped
    networks: 
      - network

networks:
  network:
    name: network

volumes:
  sqlite:
    name: sqlite