version: 3

tasks:
  default:
    desc: list tasks
    cmd: task --list-all

  gen:
    desc: build frontend
    cmd: go generate ./...

  run:
    desc: run go server
    deps:
      - gen
    cmd: go run ./...

  build:
    desc: build docker image
    cmds:
      - docker build -t=nice-wildcat:latest .